name: Tradewheel Auto Scraper

on:
  schedule:
    # Chạy mỗi 2 tuần vào thứ 2 lúc 9:00 AM UTC (4:00 PM GMT+7)
    - cron: "0 9 */14 * 1"

  # Cho phép chạy manual
  workflow_dispatch:
    inputs:
      start_page:
        description: "Start page"
        required: false
        default: "1"
      end_page:
        description: "End page"
        required: false
        default: "15"

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Cần quyền write để commit và push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          # Install Chrome
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Verify Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Create data directory
        run: mkdir -p data

      - name: Run scraper
        env:
          START_PAGE: ${{ github.event.inputs.start_page || '1' }}
          END_PAGE: ${{ github.event.inputs.end_page || '15' }}
        run: |
          cd src
          python main.py

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git add -A

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Auto scrape: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi

      - name: Notify n8n webhook
        if: success()
        run: |
          # Ưu tiên lấy file Excel được thay đổi ở commit mới nhất
          FILE_PATH=$(git log -1 --name-only --pretty="" -- data/*.xlsx | head -1 || echo "")
          if [ -n "$FILE_PATH" ] && [ -f "$FILE_PATH" ]; then
            FILE_NAME=$(basename "$FILE_PATH")
          else
            # Fallback: lấy file mới nhất theo thời gian sửa đổi
            # Tránh chọn nhầm theo thứ tự chữ cái (vd: 08_* trước 09_*)
            FILE_NAME=$(ls -t data/*.xlsx 2>/dev/null | head -1 | xargs basename || echo "")
          fi
          SCRAPE_DATE=$(date +'%Y-%m-%d %H:%M:%S')
          SCRAPE_COUNT=$(ls data/*.xlsx 2>/dev/null | wc -l || echo "0")

          if [ ! -z "$FILE_NAME" ]; then
            echo "📊 Found Excel file: $FILE_NAME"
            
            # Gọi n8n webhook với thông tin file
            curl -X POST "${{ secrets.N8N_WEBHOOK_URL }}" \
              -H "Content-Type: application/json" \
              -d '{
                "scrape_date": "'"$SCRAPE_DATE"'",
                "file_name": "'"$FILE_NAME"'",
                "file_count": '"$SCRAPE_COUNT"',
                "status": "success",
                "repository": "XuanKyUEL/tradewheel_scrape",
                "github_view_url": "https://github.com/XuanKyUEL/tradewheel_scrape/blob/main/data/'"$FILE_NAME"'",
                "download_url": "https://github.com/XuanKyUEL/tradewheel_scrape/raw/main/data/'"$FILE_NAME"'"
              }' || echo "⚠️ Failed to notify n8n webhook"
          else
            echo "❌ No Excel file found to notify"
          fi
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tradewheel-data
          path: data/
          retention-days: 90
